apiVersion: networking.istio.io/v1alpha3
kind: ServiceEntry
metadata:
  name: sleep
spec:
  hosts:
  - api-3scale-apicast-staging.apps.cluster-3c7e.3c7e.sandbox1865.opentlc.com
  ports:
  - number: 443
    name: http
    protocol: HTTPS
  resolution: DNS
  location: MESH_EXTERNAL