apiVersion: "security.istio.io/v1beta1"
kind: "RequestAuthentication"
metadata:
  name: "jwt-example"
  namespace: bookinfo
spec:
  selector:
    matchLabels:
      app: productpage
  jwtRules:
  - issuer: "https://keycloak-rhsso.apps.cluster-f4ea.f4ea.sandbox1246.opentlc.com/auth/realms/threescale-realm"
    jwksUri: "https://keycloak-rhsso.apps.cluster-f4ea.f4ea.sandbox1246.opentlc.com/auth/realms/threescale-realm/protocol/openid-connect/certs"