apiVersion: config.istio.io/v1alpha2
kind: handler
metadata:
  creationTimestamp: null
  name: basic
  namespace: istio-system
spec:
  adapter: threescale
  connection:
    address: dns:///threescale-istio-adapter:3333
  params:
    access_token: 9718IAbE0limszS3
    system_url: 'https://3scale-admin.apps.cluster-f4ea.f4ea.sandbox1246.opentlc.com'